name: CI
on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: chartboost/ruff-action@v1
      - name: Run mypy
        run: |
          pip install mypy
          mypy --strict .
